#!/usr/bin/env python3
"""Generate deterministic terminal frames from Muybridge's 1878 horse study.

This is a development-time provenance tool, not a Barbaro runtime dependency.
It requires Pillow and a local copy of the public-domain Wikimedia Commons GIF:

https://commons.wikimedia.org/wiki/File:The_Horse_in_Motion-anim.gif
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageOps


SOURCE_SHA256 = "d0ca726bdac7c2fecdf2fcfe02edcee31d938bbafedda1072c073c748f94bb9c"
SOURCE_URL = (
    "https://commons.wikimedia.org/wiki/"
    "File:The_Horse_in_Motion-anim.gif"
)
PALETTE = "█▓▒░ "
ORIGINAL_CROP = (16, 38, 326, 205)
RIDERLESS_CROP = (16, 62, 326, 205)
ORIGINAL_SCALES = {"hero": (56, 15), "compact": (36, 10)}
RIDERLESS_SCALES = {"riderless_hero": (56, 13), "riderless_compact": (36, 8)}
FACE_CONTOUR_SOURCE_X = 235
FACE_CONTOUR_SOURCE_Y_MAX = 120
HALF_BLOCK_DARK_THRESHOLD = 128

# Per-frame source-pixel profiles. Each polyline describes the horse's inferred
# top edge underneath the rider, from croup/back to neck. The generator masks
# everything above that edge between its endpoints before resampling; keeping
# this source-space data separate prevents edits to generated terminal glyphs.
RIDER_LOWER_EDGES = [
    [(162, 94), (176, 94), (188, 98), (199, 96), (208, 89), (214, 80)],
    [(164, 96), (178, 95), (190, 98), (201, 94), (210, 87), (214, 80)],
    [(164, 97), (178, 97), (190, 99), (202, 95), (211, 88), (216, 78)],
    [(164, 98), (178, 98), (191, 101), (202, 96), (211, 87), (216, 79)],
    [(164, 98), (178, 99), (191, 102), (202, 96), (211, 86), (217, 80)],
    [(164, 97), (178, 100), (190, 101), (202, 97), (211, 87), (216, 82)],
    [(164, 97), (178, 99), (191, 101), (202, 97), (211, 87), (216, 82)],
    [(164, 96), (178, 99), (190, 100), (202, 96), (211, 87), (216, 82)],
    [(164, 98), (178, 99), (190, 101), (202, 96), (211, 88), (216, 82)],
    [(164, 97), (178, 98), (190, 101), (202, 96), (211, 87), (216, 80)],
    [(164, 97), (178, 98), (190, 101), (202, 96), (211, 87), (216, 80)],
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    return parser.parse_args()


def frame_lines(
    image: Image.Image,
    crop: tuple[int, int, int, int],
    width: int,
    height: int,
    contour_from_source_x: int | None = None,
) -> list[str]:
    prepared = ImageOps.autocontrast(
        image.convert("L").crop(crop),
        cutoff=(1, 22),
    )
    density = prepared.resize((width, height), Image.Resampling.LANCZOS)
    if contour_from_source_x is not None:
        detail = prepared.resize((width, height * 2), Image.Resampling.LANCZOS)
        return face_contour_lines(
            density,
            detail,
            crop,
            width,
            height,
            contour_from_source_x,
        )
    return [
        "".join(
            density_character(density.getpixel((x, y)))
            for x in range(width)
        )
        for y in range(height)
    ]


def face_contour_lines(
    density: Image.Image,
    detail: Image.Image,
    crop: tuple[int, int, int, int],
    width: int,
    height: int,
    contour_from_source_x: int,
) -> list[str]:
    crop_width = crop[2] - crop[0]
    lines: list[str] = []
    for y in range(height):
        line: list[str] = []
        source_y = crop[1] + (y + 0.5) * (crop[3] - crop[1]) / height
        for x in range(width):
            upper = detail.getpixel((x, y * 2))
            lower = detail.getpixel((x, y * 2 + 1))
            source_x = crop[0] + (x + 0.5) * crop_width / width
            upper_dark = upper < HALF_BLOCK_DARK_THRESHOLD
            lower_dark = lower < HALF_BLOCK_DARK_THRESHOLD
            in_face = (
                source_x >= contour_from_source_x
                and source_y <= FACE_CONTOUR_SOURCE_Y_MAX
            )
            if in_face and upper_dark and not lower_dark:
                line.append("▀")
            else:
                line.append(density_character(density.getpixel((x, y))))
        lines.append("".join(line))
    return lines


def density_character(value: int) -> str:
    return PALETTE[min(len(PALETTE) - 1, value * len(PALETTE) // 256)]


def without_rider(image: Image.Image, index: int) -> Image.Image:
    frame = image.convert("L").copy()
    edge = RIDER_LOWER_EDGES[index]
    polygon = [(edge[0][0], 0), (edge[-1][0], 0), *reversed(edge)]
    ImageDraw.Draw(frame).polygon(polygon, fill=255)
    return frame


def typescript(frames: dict[str, list[list[str]]]) -> str:
    blocks: list[str] = [
        "// Generated by scripts/generate-horse-frames.py. Do not hand-edit.",
        "// Source: Eadweard Muybridge, Sallie Gardner at a Gallop (1878).",
        "// Public-domain reference: " + SOURCE_URL,
        "// Source SHA-256: " + SOURCE_SHA256,
        "",
    ]
    for scale, values in frames.items():
        name = f"HORSE_{scale.upper()}_FRAMES"
        blocks.append(f"export const {name} = [")
        for frame in values:
            blocks.append("  [")
            blocks.extend(
                f"    {json.dumps(line, ensure_ascii=False)}," for line in frame
            )
            blocks.append("  ],")
        blocks.append("] as const;")
        blocks.append("")
    return "\n".join(blocks)


def main() -> None:
    args = parse_args()
    source_bytes = args.source.read_bytes()
    digest = hashlib.sha256(source_bytes).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(
            f"source SHA-256 mismatch: expected {SOURCE_SHA256}, received {digest}"
        )

    source = Image.open(args.source)
    scale_names = [*ORIGINAL_SCALES, *RIDERLESS_SCALES]
    frames: dict[str, list[list[str]]] = {scale: [] for scale in scale_names}
    for index in range(source.n_frames):
        source.seek(index)
        original = source.convert("L")
        riderless = without_rider(source, index)
        for scale, (width, height) in ORIGINAL_SCALES.items():
            frames[scale].append(
                frame_lines(original, ORIGINAL_CROP, width, height)
            )
        for scale, (width, height) in RIDERLESS_SCALES.items():
            frames[scale].append(
                frame_lines(
                    riderless,
                    RIDERLESS_CROP,
                    width,
                    height,
                    contour_from_source_x=FACE_CONTOUR_SOURCE_X,
                )
            )

    if source.n_frames != 11:
        raise SystemExit(f"expected 11 source frames, received {source.n_frames}")
    args.output.write_text(typescript(frames), encoding="utf-8")


if __name__ == "__main__":
    main()
